package com.fang.taipeitour.ui.theme.color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val TreeLight =
    lightColorScheme(
        primary = Color(0xFF326B23),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFB3F39B),
        onPrimaryContainer = Color(0xFF022100),
        secondary = Color(0xFF54624D),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD7E8CC),
        onSecondaryContainer = Color(0xFF121F0E),
        tertiary = Color(0xFF585C7E),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFDFE0FF),
        onTertiaryContainer = Color(0xFF151937),
        error = Color(0xFFBA1A1A),
        errorContainer = Color(0xFFFFDAD6),
        onError = Color(0xFFFFFFFF),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFDFDF6),
        onBackground = Color(0xFF1A1C18),
        surface = Color(0xFFFDFDF6),
        onSurface = Color(0xFF1A1C18),
        surfaceVariant = Color(0xFFDFE4D7),
        onSurfaceVariant = Color(0xFF43483F),
        outline = Color(0xFF73796E),
        inverseOnSurface = Color(0xFFF1F1EA),
        inverseSurface = Color(0xFF2F312D),
        inversePrimary = Color(0xFF98D782),
        surfaceTint = Color(0xFF326B23),
        outlineVariant = Color(0xFFC3C8BC),
        scrim = Color(0xFF000000),
    )

val TreeDark =
    darkColorScheme(
        primary = Color(0xFF98D782),
        onPrimary = Color(0xFF073900),
        primaryContainer = Color(0xFF19520C),
        onPrimaryContainer = Color(0xFFB3F39B),
        secondary = Color(0xFFBCCBB1),
        onSecondary = Color(0xFF273421),
        secondaryContainer = Color(0xFF3D4B36),
        onSecondaryContainer = Color(0xFFD7E8CC),
        tertiary = Color(0xFFC1C4EB),
        onTertiary = Color(0xFF2A2E4D),
        tertiaryContainer = Color(0xFF404565),
        onTertiaryContainer = Color(0xFFDFE0FF),
        error = Color(0xFFFFB4AB),
        errorContainer = Color(0xFF93000A),
        onError = Color(0xFF690005),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF1A1C18),
        onBackground = Color(0xFFE2E3DC),
        surface = Color(0xFF1A1C18),
        onSurface = Color(0xFFE2E3DC),
        surfaceVariant = Color(0xFF43483F),
        onSurfaceVariant = Color(0xFFC3C8BC),
        outline = Color(0xFF8D9387),
        inverseOnSurface = Color(0xFF1A1C18),
        inverseSurface = Color(0xFFE2E3DC),
        inversePrimary = Color(0xFF326B23),
        surfaceTint = Color(0xFF98D782),
        outlineVariant = Color(0xFF43483F),
        scrim = Color(0xFF000000),
    )
